---
functional:
  - Возможность регистрации на сайте через email и пароль
  - Возможность авторизации через созданный на сайте аккаунт 
  - Есть мультиязычность интерфейса сайта
  - У пользователя должна быть возможность менять аватар
  - Возможность отвязать аккаунт GitHub
  - Возможность создать новый Task
  - Возможность просмотреть профиль других игроков
  - Возможность выбрать баттл с любым пользователем
  - Есть тренировочный режим с ботом
  - Возможность менять никнейм
  - Возможность выбрать задачу для баттла
  - Возможность создания турниров
  - На сайте присутствует общий рейтинг игроков
  - Возможность просмотреть записи завершенных игр
  - Возможность смотреть online активные игры
non-functional:
  - Таблица с рейтингом игроков расположена на главной странице
  - Цвет кнопки "CREATE A GAME" зеленый
  - Сайт должен быстро обрабатывать запросы
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
implicit:
  - В шапке сайта справа отображается никнейм пользователя с дополнительной информацией
  - У пользователя есть возможность изменять пароль
  - Возможность просмотреть свой профиль
